CREATE USER 'root'@'%' IDENTIFIED BY '!msd4SQLAdmin%'; 
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
CREATE DATABASE IF NOT EXISTS dev;
CREATE DATABASE IF NOT EXISTS test;
-- USE dev;
-- CREATE TABLE IF NOT EXISTS (...);